# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import datanode_pb2 as datanode__pb2


class DataNodeServiceStub(object):
    """Servicio que ofrece DataNode
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreBlock = channel.unary_unary(
                '/datanode.DataNodeService/StoreBlock',
                request_serializer=datanode__pb2.StoreBlockRequest.SerializeToString,
                response_deserializer=datanode__pb2.StoreBlockResponse.FromString,
                )
        self.RetrieveBlock = channel.unary_unary(
                '/datanode.DataNodeService/RetrieveBlock',
                request_serializer=datanode__pb2.RetrieveBlockRequest.SerializeToString,
                response_deserializer=datanode__pb2.RetrieveBlockResponse.FromString,
                )


class DataNodeServiceServicer(object):
    """Servicio que ofrece DataNode
    """

    def StoreBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreBlock,
                    request_deserializer=datanode__pb2.StoreBlockRequest.FromString,
                    response_serializer=datanode__pb2.StoreBlockResponse.SerializeToString,
            ),
            'RetrieveBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveBlock,
                    request_deserializer=datanode__pb2.RetrieveBlockRequest.FromString,
                    response_serializer=datanode__pb2.RetrieveBlockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datanode.DataNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataNodeService(object):
    """Servicio que ofrece DataNode
    """

    @staticmethod
    def StoreBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datanode.DataNodeService/StoreBlock',
            datanode__pb2.StoreBlockRequest.SerializeToString,
            datanode__pb2.StoreBlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datanode.DataNodeService/RetrieveBlock',
            datanode__pb2.RetrieveBlockRequest.SerializeToString,
            datanode__pb2.RetrieveBlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
