# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datanode.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tanode.proto\x12\x08\x64\x61tanode\"3\n\x11StoreBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"%\n\x12StoreBlockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x14RetrieveBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"%\n\x15RetrieveBlockResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xac\x01\n\x0f\x44\x61taNodeService\x12G\n\nStoreBlock\x12\x1b.datanode.StoreBlockRequest\x1a\x1c.datanode.StoreBlockResponse\x12P\n\rRetrieveBlock\x12\x1e.datanode.RetrieveBlockRequest\x1a\x1f.datanode.RetrieveBlockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datanode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STOREBLOCKREQUEST']._serialized_start=28
  _globals['_STOREBLOCKREQUEST']._serialized_end=79
  _globals['_STOREBLOCKRESPONSE']._serialized_start=81
  _globals['_STOREBLOCKRESPONSE']._serialized_end=118
  _globals['_RETRIEVEBLOCKREQUEST']._serialized_start=120
  _globals['_RETRIEVEBLOCKREQUEST']._serialized_end=160
  _globals['_RETRIEVEBLOCKRESPONSE']._serialized_start=162
  _globals['_RETRIEVEBLOCKRESPONSE']._serialized_end=199
  _globals['_DATANODESERVICE']._serialized_start=202
  _globals['_DATANODESERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
